### ISSUE TITLE
Where are the "IDs" for the syscalls declared?

### ISSUE THREAD

**Issue by L-as** [vekatze/neut-core#1]
I am adding aarch64 support, but I can't figure out how to fix the incorrect syscall IDs that neut is using, e.g. `write` is putting 1 into x8 instead of 0x40.

**Comment by vekatze** [comment]
The IDs are declared in `src/Data/Syscall.hs`.
For example, the `1` of `write` corresponds to the `1` of `("write", 1)` in the file.

**Comment by L-as** [comment]
Oh, so it's not even declared here! Thanks.
